import { Router } from 'express';
import { authMiddleware, requireRole } from '../services/authMiddleware.js';
import { getEnergie, postAddSource, postEditSource, postDeleteSource, postSaveSeuil, postDeleteSeuil, apiGetNotifications, apiClearNotifications } from '../controllers/energieController.js';
const router = Router();
router.get('/',                        authMiddleware, requireRole('SUPER_ADMIN', 'ADMIN'), getEnergie);
router.post('/sources/add',            authMiddleware, requireRole('SUPER_ADMIN', 'ADMIN'), postAddSource);
router.post('/sources/:id/edit',       authMiddleware, requireRole('SUPER_ADMIN', 'ADMIN'), postEditSource);
router.post('/sources/:id/delete',     authMiddleware, requireRole('SUPER_ADMIN'),           postDeleteSource);
router.post('/seuils/save',            authMiddleware, requireRole('SUPER_ADMIN', 'ADMIN'), postSaveSeuil);
router.post('/seuils/:id/delete',      authMiddleware, requireRole('SUPER_ADMIN', 'ADMIN'), postDeleteSeuil);
router.get('/notifications',           authMiddleware, apiGetNotifications);
router.post('/notifications/clear',    authMiddleware, apiClearNotifications);
export { router as energieRouter };
